# Generated by Django 4.1.6 on 2023-02-14 20:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='groupInfo',
            fields=[
                ('groupID', models.AutoField(primary_key=True, serialize=False)),
                ('groupName', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='processElements',
            fields=[
                ('processElementID', models.AutoField(primary_key=True, serialize=False)),
                ('elementName', models.CharField(max_length=60)),
                ('elementValue', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='processInfo',
            fields=[
                ('processID', models.AutoField(primary_key=True, serialize=False)),
                ('processName', models.CharField(max_length=60)),
                ('processDescription', models.TextField()),
                ('processType', models.CharField(choices=[('Integration', 'Integration'), ('Application', 'Application'), ('Dashboard', 'Dashboard')], max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='processUpdateLog',
            fields=[
                ('ID', models.AutoField(primary_key=True, serialize=False)),
                ('userID', models.CharField(max_length=30)),
                ('valueBefore', models.CharField(max_length=30)),
                ('valueAfter', models.CharField(max_length=30)),
                ('timestamp', models.DateTimeField(auto_now=True)),
                ('groupID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Sample.groupinfo')),
                ('processElementID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Sample.processelements')),
                ('processID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Sample.processinfo')),
            ],
        ),
        migrations.AddField(
            model_name='processelements',
            name='processID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Sample.processinfo'),
        ),
        migrations.CreateModel(
            name='processAccessInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('groupID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Sample.groupinfo')),
                ('processID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Sample.processinfo')),
            ],
        ),
    ]
