# Generated by Django 4.1.6 on 2023-03-06 15:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Sample', '0002_alter_processupdatelog_timestamp'),
    ]

    operations = [
        migrations.CreateModel(
            name='scheduledUpdatesInfo',
            fields=[
                ('ID', models.AutoField(primary_key=True, serialize=False)),
                ('userID', models.CharField(max_length=30)),
                ('valueBefore', models.CharField(max_length=30)),
                ('valueAfter', models.CharField(max_length=30)),
                ('dateScheduled', models.DateField()),
                ('groupID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Sample.groupinfo')),
                ('processElementID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Sample.processelements')),
                ('processID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Sample.processinfo')),
            ],
        ),
    ]
